package org.example.wavepilot.artifact;

public enum ArtifactType {
    EXPERIMENT_SPEC,
    EXPERIMENT_PLAN,
    ACCURACY_CSV,
    ACCURACY_CURVE,
    MAT_RESULT,
    RUN_LOG,
    SUMMARY_JSON,
    FINAL_REPORT,
    REPLAY_MANIFEST,
    REPLAY_COMPARISON,
    EVAL_REPORT,
    EVAL_CASE_RESULTS,
    EVAL_COMPARISON,
    RETRIEVAL_EVAL_JSON,
    RETRIEVAL_EVAL_MARKDOWN,
    AGENT_RUN_TRACE,
    AGENT_EVAL_REPORT,
    AGENT_EVAL_COMPARISON
}
